### PR TITLE
get rid of Compat requirement

### LINKED ISSUE #11: update Compat requirements
i can't install LsqFit alongside Optim master because LsqFit requires OptimBase and OptimBase requires  Compat 0.18 and Optim requires Compat 3.2-3.6.  is this package actually still required by LsqFit?  it hasn't been updated in years.

### PR DESCRIPTION
**Pull request by bjarthur**
fixes https://github.com/JuliaNLSolvers/OptimBase.jl/issues/11

### CODE REVIEW

**Comment by bjarthur** [comment]
this is ready i think.  comments?

**Comment by martinholters** [comment]
I'm also a bit hampered by #11 and would appreciate it if this could merged and a new release tagged soonish.

**Comment by Vaibhavdixit02** [comment]
Bump @pkofod

**Comment by ChrisRackauckas** [comment]
and add CompatHelper please.

**Pull request merged**
